package kingaidra.ai.task;

public enum TaskType {
    DECOM_REFACTOR_FUNC_PARAM_VAR,
    DECOM_REFACTOR_DATATYPE,
    CHAT,
    CHAT_EXPLAIN_DECOM,
    CHAT_EXPLAIN_ASM,
    CHAT_DECOM_ASM,
    CHAT_EXPLAIN_STRINGS,
    ADD_COMMENTS,
    DECOM_RESOLVE_DATATYPE,
    KEYFUNC_CALLTREE,
}
