package kingaidra.ai.task;

public enum TaskType {
    DECOM_REFACTOR_FUNC_PARAM_VAR,
    DECOM_REFACTOR_DATATYPE,
    CHAT,
    ADD_COMMENTS,
    DECOM_RESOLVE_DATATYPE,
    KEYFUNC_STRING,
    KEYFUNC_CALLTREE,
}
